// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp4ZpzxIsU85k-_5M41cQczxOFUW_zrW8',
    appId: '1:460022449022:web:ddd07c4bb03de4ad83692f',
    messagingSenderId: '460022449022',
    projectId: 'carryvibe-efood',
    authDomain: 'carryvibe-efood.firebaseapp.com',
    storageBucket: 'carryvibe-efood.appspot.com',
    measurementId: 'G-3E7B3ZQ0CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRX6egTGnMZ0O69Mjs9LYipZDQqcy3zM',
    appId: '1:460022449022:android:0b5951b91ad6824383692f',
    messagingSenderId: '460022449022',
    projectId: 'carryvibe-efood',
    storageBucket: 'carryvibe-efood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuyKvsipOl0IZIJWfjQGn5TXntctMfDVE',
    appId: '1:460022449022:ios:df655f363bc865c183692f',
    messagingSenderId: '460022449022',
    projectId: 'carryvibe-efood',
    storageBucket: 'carryvibe-efood.appspot.com',
    androidClientId: '460022449022-tin7tsabgtgd6s90r06osf811l88iu1v.apps.googleusercontent.com',
    iosClientId: '460022449022-fghhq8ush0guob0ggeu3ptja4fj0ihlj.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.eFood',
  );
}
